name = "GregoryIntegrators"
uuid = "49db6aea-5aa9-4eed-8ff3-7f43b40eac63"
authors = ["Lukas Grunwald <lukas.grunwald@rwth-aachen.de>"]
version = "0.1.0"

[deps]
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"

[extras]
PConv = "ddafdd3f-bffb-4613-bf4c-94e59b398e54"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets", "QuadGK", "PConv"]
